version: '3'

services:
  velux-to-mqtt-gw:
    container_name: velux-to-mqtt-gw
    image: pharndt/velux-to-mqtt-gw:${ENV:-latest}
    volumes:
      - ./config.json:/var/lib/velux-to-mqtt-gw/config.json:ro
    restart: unless-stopped
